import Header from "@/components/organisms/Header";
import "./globals.css";
import Main from "@/components/organisms/Main";

export const metadata = {
  title: "Flavor Guide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <Main>{children}</Main>
      </body>
    </html>
  );
}
