import Header from "@/components/organisms/Header";
import "./globals.css";
import Main from "@/components/organisms/Main";
import { Providers } from "./provider";

export const metadata = {
  title: "Flavor Guide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header></Header>
          <Main>{children}</Main>
        </Providers>
      </body>
    </html>
  );
}
